language: node_js
addons:
  chrome: stable
env:
  matrix:
  - TEST_SUITE=lint
  - TEST_SUITE=build
  - TEST_SUITE=unit
  - TEST_SUITE=docs
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm run postinstall
script:
- npm run test:$TEST_SUITE
after_success:
- npm install coveralls && cat ./coverage/lcov.info | coveralls